version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
      paper:
        patterns:
          - "io.papermc.paper*"
          - "dev.folia*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
